# Test Trivy
apiVersion: v1
kind: Namespace
metadata:
  name: ns-nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: ns-nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="fr">
    <head>
      <meta charset="UTF-8" />
      <title>Bienvenue - ns-nginx</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          background: linear-gradient(135deg, #1f2933, #111827);
          color: #f9fafb;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          height: 100vh;
          margin: 0;
        }
        h1 {
          font-size: 3rem;
          margin-bottom: 0.5rem;
        }
        p {
          font-size: 1.1rem;
          opacity: 0.9;
        }
        .badge {
          margin-top: 1rem;
          padding: 0.4rem 0.8rem;
          border-radius: 999px;
          border: 1px solid #4b5563;
          font-size: 0.85rem;
          text-transform: uppercase;
          letter-spacing: 0.08em;
        }
      </style>
    </head>
    <body>
      <h1>Nginx 🚀</h1>
      <p>Déployé via ArgoCD sur mon cluster Kubernetes.</p>
      <div class="badge">NodePort : 30180</div>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ns-nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: dockerhub-cred
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-index
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: nginx-index
          configMap:
            name: nginx-index
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ns-nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30180
